### ISSUE TITLE
Typos/Clarity issues in Introduction and Setup sections of README

### ISSUE THREAD

**Issue by Llamahawk** [mssalstrom/Group5-repo-projects#21]
Introduction Typo:
  - Need a hyphen after Ever's name under "Contributors"

Setup Typo:
  - repl (supposed to be repo i believe)
 
 Setup Clarity:
 - Reorder setup steps for clarity by:
   - Step 1 - start with requirements.txt download
   - Step 1.b - verify installations with --version CLI
   - if failed, direct user to optional step 1.c - CLI install instructions (flask install and verification as 1.c, selenium 1.d, or whatever scheme makes most sense to you)
   - if successful, skip to Step 2 - flask setup (running app.py)
 - Replace "Test x installation" with "Verify x installation"
 - Test installations with --version CLI commands instead of current method
 - Create distinct section within setup for opening flask for readability
 - Create instructions for how to download selenium branch on user's computer/IDE at beginning of setup (assumes user would be extremely new)

**Comment by Llamahawk** [comment]
Need to instruct user to check versions after requirements.txt install. 
If the requirements.txt install worked then instruct the user to skip the individual flask/selenium installs since they are redundant

**Comment by DSDouglas** [comment]
recommended changes added to read me.
